version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot-renew.sh:/etc/cron.daily/certbot-renew.sh
    entrypoint: /bin/sh -c "nginx -g 'daemon off;' & /etc/cron.daily/certbot-renew.sh && tail -f /dev/null"
    depends_on:
      - django
      - fastapi

  django:
    build: ./django
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  fastapi:
    build: ./fastapi
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
